# Application Name Configuration
env.spring.application.name=shopping-list-gestor-service

# Server Port Number Configuration
env.server.port=9000
env.server.address=0.0.0.0

# MYSQL Configuration
env.spring.datasource.url=jdbc:postgresql://db_shoppinglist_gestor_user:h9ZReOWO6PqJKXcCqUTMsAaDtbVDrHp9@dpg-d9u7v6142hec739pna40-a/db_shoppinglist_gestor
env.spring.datasource.username=db_shoppinglist_gestor_user
env.spring.datasource.password=h9ZReOWO6PqJKXcCqUTMsAaDtbVDrHp9
env.spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
env.spring.jpa.hibernate.ddl-auto=update
end.spring.jpa.show-sql=true