# Application Name Configuration
env.spring.application.name=shopping-list-gestor-service

# Server Port Number Configuration
env.server.port=9000
env.server.address=0.0.0.0

# MYSQL Configuration
env.spring.datasource.url=jdbc:mysql://localhost:3306/db_shoppinglist_gestor?useSSL=false
env.spring.datasource.username=FranRicoDev
env.spring.datasource.password=FranRicoDev123456789!
env.spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
env.spring.jpa.hibernate.ddl-auto=update
end.spring.jpa.show-sql=true